---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: hw5
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  strategy: 
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - image: postgres:10.13
        name: postgres
        ports:
        - containerPort: 5432
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - name: pgdata
          mountPath: /var/lib/postgresql/data/
        env:
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        - name: POSTGRES_DB
          value: testdatabase
        - name: POSTGRES_USER
          value: testuser 
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: all-secrets
              key: pg_pass
      volumes:
      - name: pgdata
        persistentVolumeClaim:
          claimName: pgdata
