---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redmine
  namespace: hw5
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redmine
  strategy: 
    type: Recreate
  template:
    metadata:
      labels:
        app: redmine
    spec:
      containers:
      - image: redmine:4.1.1
        name: redmine
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 500m
            memory: 500Mi
        env:
        - name: REDMINE_DB_POSTGRES
          value: database
        - name: REDMINE_DB_DATABASE
          value: testdatabase
        - name: REDMINE_DB_USERNAME
          value: testuser 
        - name: REDMINE_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: all-secrets
              key: pg_pass
        - name: REDMINE_SECRET_KEY_BASE
          valueFrom:
            secretKeyRef:
              name: all-secrets
              key: rm_pass
