---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: gb4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - image: postgres:10.13
        name: postgres
        env:
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata		
        - name: POSTGRES_DB
          value: testdatabase
        - name: POSTGRES_USER
          value: testuser
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pg-secret
              key: secret
        ports:
        - containerPort: 5432
          protocol: TCP
        volumeMounts:
        - name: pgdata
          mountPath: /var/lib/postgresql/data/
      volumes:
      - name: pgdata
        persistentVolumeClaim:
          claimName: pgdata
